name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7.0.1

      - name: Install and Build 🔧
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: built-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
